// Code generated by protoc-gen-go.
// source: Location.proto
// DO NOT EDIT!

/*
Package Report is a generated protocol buffer package.

It is generated from these files:
	Location.proto

It has these top-level messages:
	WGS84
	GCJ02
	MobileCell
	Wifi
	RFID
	TagMacRssi
	Indoor
	IndoorIntensity
	Location
	MobileLocationData
	LocationReport
*/
package Report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 位置坐标类型
type Location_LocationType int32

const (
	Location_EWGS84           Location_LocationType = 0
	Location_EGCJ02           Location_LocationType = 1
	Location_EMobileCell      Location_LocationType = 2
	Location_ERFID            Location_LocationType = 3
	Location_EIndoor          Location_LocationType = 4
	Location_EIndoorIntensity Location_LocationType = 5
	Location_WIFI             Location_LocationType = 6
)

var Location_LocationType_name = map[int32]string{
	0: "EWGS84",
	1: "EGCJ02",
	2: "EMobileCell",
	3: "ERFID",
	4: "EIndoor",
	5: "EIndoorIntensity",
	6: "WIFI",
}
var Location_LocationType_value = map[string]int32{
	"EWGS84":           0,
	"EGCJ02":           1,
	"EMobileCell":      2,
	"ERFID":            3,
	"EIndoor":          4,
	"EIndoorIntensity": 5,
	"WIFI":             6,
}

func (x Location_LocationType) Enum() *Location_LocationType {
	p := new(Location_LocationType)
	*p = x
	return p
}
func (x Location_LocationType) String() string {
	return proto.EnumName(Location_LocationType_name, int32(x))
}
func (x *Location_LocationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Location_LocationType_value, data, "Location_LocationType")
	if err != nil {
		return err
	}
	*x = Location_LocationType(value)
	return nil
}
func (Location_LocationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

// 位置信息来源
type Location_FromType int32

const (
	Location_ETerminal Location_FromType = 0
	Location_EPlatform Location_FromType = 1
)

var Location_FromType_name = map[int32]string{
	0: "ETerminal",
	1: "EPlatform",
}
var Location_FromType_value = map[string]int32{
	"ETerminal": 0,
	"EPlatform": 1,
}

func (x Location_FromType) Enum() *Location_FromType {
	p := new(Location_FromType)
	*p = x
	return p
}
func (x Location_FromType) String() string {
	return proto.EnumName(Location_FromType_name, int32(x))
}
func (x *Location_FromType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Location_FromType_value, data, "Location_FromType")
	if err != nil {
		return err
	}
	*x = Location_FromType(value)
	return nil
}
func (Location_FromType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 1} }

// 84坐标信息
type WGS84 struct {
	LngE6            *int32 `protobuf:"varint,1,req,name=lng_e6,def=0" json:"lng_e6,omitempty"`
	LatE6            *int32 `protobuf:"varint,2,req,name=lat_e6,def=0" json:"lat_e6,omitempty"`
	Altitude         *int32 `protobuf:"varint,5,opt,name=altitude,def=0" json:"altitude,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *WGS84) Reset()                    { *m = WGS84{} }
func (m *WGS84) String() string            { return proto.CompactTextString(m) }
func (*WGS84) ProtoMessage()               {}
func (*WGS84) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_WGS84_LngE6 int32 = 0
const Default_WGS84_LatE6 int32 = 0
const Default_WGS84_Altitude int32 = 0

func (m *WGS84) GetLngE6() int32 {
	if m != nil && m.LngE6 != nil {
		return *m.LngE6
	}
	return Default_WGS84_LngE6
}

func (m *WGS84) GetLatE6() int32 {
	if m != nil && m.LatE6 != nil {
		return *m.LatE6
	}
	return Default_WGS84_LatE6
}

func (m *WGS84) GetAltitude() int32 {
	if m != nil && m.Altitude != nil {
		return *m.Altitude
	}
	return Default_WGS84_Altitude
}

// 02坐标信息
type GCJ02 struct {
	LngE6            *int32 `protobuf:"varint,1,req,name=lng_e6,def=0" json:"lng_e6,omitempty"`
	LatE6            *int32 `protobuf:"varint,2,req,name=lat_e6,def=0" json:"lat_e6,omitempty"`
	Altitude         *int32 `protobuf:"varint,5,opt,name=altitude,def=0" json:"altitude,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GCJ02) Reset()                    { *m = GCJ02{} }
func (m *GCJ02) String() string            { return proto.CompactTextString(m) }
func (*GCJ02) ProtoMessage()               {}
func (*GCJ02) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_GCJ02_LngE6 int32 = 0
const Default_GCJ02_LatE6 int32 = 0
const Default_GCJ02_Altitude int32 = 0

func (m *GCJ02) GetLngE6() int32 {
	if m != nil && m.LngE6 != nil {
		return *m.LngE6
	}
	return Default_GCJ02_LngE6
}

func (m *GCJ02) GetLatE6() int32 {
	if m != nil && m.LatE6 != nil {
		return *m.LatE6
	}
	return Default_GCJ02_LatE6
}

func (m *GCJ02) GetAltitude() int32 {
	if m != nil && m.Altitude != nil {
		return *m.Altitude
	}
	return Default_GCJ02_Altitude
}

// 基站定位信息
type MobileCell struct {
	Mcc              *int32 `protobuf:"varint,1,req,name=mcc,def=406" json:"mcc,omitempty"`
	Mnc              *int32 `protobuf:"varint,2,req,name=mnc" json:"mnc,omitempty"`
	Lac              *int32 `protobuf:"varint,3,req,name=lac" json:"lac,omitempty"`
	Cellid           *int32 `protobuf:"varint,4,req,name=cellid" json:"cellid,omitempty"`
	Ss               *int32 `protobuf:"varint,5,opt,name=ss" json:"ss,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MobileCell) Reset()                    { *m = MobileCell{} }
func (m *MobileCell) String() string            { return proto.CompactTextString(m) }
func (*MobileCell) ProtoMessage()               {}
func (*MobileCell) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_MobileCell_Mcc int32 = 406

func (m *MobileCell) GetMcc() int32 {
	if m != nil && m.Mcc != nil {
		return *m.Mcc
	}
	return Default_MobileCell_Mcc
}

func (m *MobileCell) GetMnc() int32 {
	if m != nil && m.Mnc != nil {
		return *m.Mnc
	}
	return 0
}

func (m *MobileCell) GetLac() int32 {
	if m != nil && m.Lac != nil {
		return *m.Lac
	}
	return 0
}

func (m *MobileCell) GetCellid() int32 {
	if m != nil && m.Cellid != nil {
		return *m.Cellid
	}
	return 0
}

func (m *MobileCell) GetSs() int32 {
	if m != nil && m.Ss != nil {
		return *m.Ss
	}
	return 0
}

type Wifi struct {
	Mac              *string `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"`
	Signal           *string `protobuf:"bytes,2,opt,name=signal" json:"signal,omitempty"`
	Ssid             *string `protobuf:"bytes,3,opt,name=ssid" json:"ssid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Wifi) Reset()                    { *m = Wifi{} }
func (m *Wifi) String() string            { return proto.CompactTextString(m) }
func (*Wifi) ProtoMessage()               {}
func (*Wifi) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Wifi) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *Wifi) GetSignal() string {
	if m != nil && m.Signal != nil {
		return *m.Signal
	}
	return ""
}

func (m *Wifi) GetSsid() string {
	if m != nil && m.Ssid != nil {
		return *m.Ssid
	}
	return ""
}

// 射频识别定位信息
type RFID struct {
	Id               *int32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RFID) Reset()                    { *m = RFID{} }
func (m *RFID) String() string            { return proto.CompactTextString(m) }
func (*RFID) ProtoMessage()               {}
func (*RFID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RFID) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

// 室内定位信息
type TagMacRssi struct {
	TagMac           *int64   `protobuf:"varint,1,opt,name=tagMac" json:"tagMac,omitempty"`
	Rssi             *float64 `protobuf:"fixed64,2,opt,name=rssi" json:"rssi,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TagMacRssi) Reset()                    { *m = TagMacRssi{} }
func (m *TagMacRssi) String() string            { return proto.CompactTextString(m) }
func (*TagMacRssi) ProtoMessage()               {}
func (*TagMacRssi) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TagMacRssi) GetTagMac() int64 {
	if m != nil && m.TagMac != nil {
		return *m.TagMac
	}
	return 0
}

func (m *TagMacRssi) GetRssi() float64 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

// 室内定位信息
type Indoor struct {
	RingMac          *string       `protobuf:"bytes,1,opt,name=ringMac" json:"ringMac,omitempty"`
	Batt             *int32        `protobuf:"varint,2,opt,name=batt" json:"batt,omitempty"`
	TagMacRssi       []*TagMacRssi `protobuf:"bytes,3,rep,name=tagMacRssi" json:"tagMacRssi,omitempty"`
	DegreeX          *float64      `protobuf:"fixed64,4,opt,name=degreeX" json:"degreeX,omitempty"`
	DegreeY          *float64      `protobuf:"fixed64,5,opt,name=degreeY" json:"degreeY,omitempty"`
	DegreeZ          *float64      `protobuf:"fixed64,6,opt,name=degreeZ" json:"degreeZ,omitempty"`
	Alarm            *int32        `protobuf:"varint,7,opt,name=alarm" json:"alarm,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *Indoor) Reset()                    { *m = Indoor{} }
func (m *Indoor) String() string            { return proto.CompactTextString(m) }
func (*Indoor) ProtoMessage()               {}
func (*Indoor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Indoor) GetRingMac() string {
	if m != nil && m.RingMac != nil {
		return *m.RingMac
	}
	return ""
}

func (m *Indoor) GetBatt() int32 {
	if m != nil && m.Batt != nil {
		return *m.Batt
	}
	return 0
}

func (m *Indoor) GetTagMacRssi() []*TagMacRssi {
	if m != nil {
		return m.TagMacRssi
	}
	return nil
}

func (m *Indoor) GetDegreeX() float64 {
	if m != nil && m.DegreeX != nil {
		return *m.DegreeX
	}
	return 0
}

func (m *Indoor) GetDegreeY() float64 {
	if m != nil && m.DegreeY != nil {
		return *m.DegreeY
	}
	return 0
}

func (m *Indoor) GetDegreeZ() float64 {
	if m != nil && m.DegreeZ != nil {
		return *m.DegreeZ
	}
	return 0
}

func (m *Indoor) GetAlarm() int32 {
	if m != nil && m.Alarm != nil {
		return *m.Alarm
	}
	return 0
}

// 室内蓝牙信号强度信息
type IndoorIntensity struct {
	Imei             *string  `protobuf:"bytes,1,req,name=imei" json:"imei,omitempty"`
	BtId             *int64   `protobuf:"varint,2,req,name=btId" json:"btId,omitempty"`
	Rssi             *float64 `protobuf:"fixed64,3,req,name=rssi" json:"rssi,omitempty"`
	FingerId         *string  `protobuf:"bytes,4,req,name=fingerId" json:"fingerId,omitempty"`
	Loc              *string  `protobuf:"bytes,5,req,name=loc" json:"loc,omitempty"`
	Orientation      *string  `protobuf:"bytes,6,req,name=orientation" json:"orientation,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *IndoorIntensity) Reset()                    { *m = IndoorIntensity{} }
func (m *IndoorIntensity) String() string            { return proto.CompactTextString(m) }
func (*IndoorIntensity) ProtoMessage()               {}
func (*IndoorIntensity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IndoorIntensity) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *IndoorIntensity) GetBtId() int64 {
	if m != nil && m.BtId != nil {
		return *m.BtId
	}
	return 0
}

func (m *IndoorIntensity) GetRssi() float64 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *IndoorIntensity) GetFingerId() string {
	if m != nil && m.FingerId != nil {
		return *m.FingerId
	}
	return ""
}

func (m *IndoorIntensity) GetLoc() string {
	if m != nil && m.Loc != nil {
		return *m.Loc
	}
	return ""
}

func (m *IndoorIntensity) GetOrientation() string {
	if m != nil && m.Orientation != nil {
		return *m.Orientation
	}
	return ""
}

// 定位信息
type Location struct {
	Locationtype     *Location_LocationType `protobuf:"varint,1,req,name=locationtype,enum=Report.Location_LocationType" json:"locationtype,omitempty"`
	From             *Location_FromType     `protobuf:"varint,2,req,name=from,enum=Report.Location_FromType" json:"from,omitempty"`
	Wgs84            *WGS84                 `protobuf:"bytes,3,opt,name=wgs84" json:"wgs84,omitempty"`
	Gcj02            *GCJ02                 `protobuf:"bytes,4,opt,name=gcj02" json:"gcj02,omitempty"`
	Cells            []*MobileCell          `protobuf:"bytes,5,rep,name=cells" json:"cells,omitempty"`
	Indoor           *Indoor                `protobuf:"bytes,6,opt,name=indoor" json:"indoor,omitempty"`
	Intensity        *IndoorIntensity       `protobuf:"bytes,7,opt,name=intensity" json:"intensity,omitempty"`
	Wifis            []*Wifi                `protobuf:"bytes,8,rep,name=wifis" json:"wifis,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Location) GetLocationtype() Location_LocationType {
	if m != nil && m.Locationtype != nil {
		return *m.Locationtype
	}
	return Location_EWGS84
}

func (m *Location) GetFrom() Location_FromType {
	if m != nil && m.From != nil {
		return *m.From
	}
	return Location_ETerminal
}

func (m *Location) GetWgs84() *WGS84 {
	if m != nil {
		return m.Wgs84
	}
	return nil
}

func (m *Location) GetGcj02() *GCJ02 {
	if m != nil {
		return m.Gcj02
	}
	return nil
}

func (m *Location) GetCells() []*MobileCell {
	if m != nil {
		return m.Cells
	}
	return nil
}

func (m *Location) GetIndoor() *Indoor {
	if m != nil {
		return m.Indoor
	}
	return nil
}

func (m *Location) GetIntensity() *IndoorIntensity {
	if m != nil {
		return m.Intensity
	}
	return nil
}

func (m *Location) GetWifis() []*Wifi {
	if m != nil {
		return m.Wifis
	}
	return nil
}

// 移动定位扩展信息
type MobileLocationData struct {
	Battery          *int32 `protobuf:"varint,1,req,name=battery" json:"battery,omitempty"`
	Speed            *int32 `protobuf:"varint,2,req,name=speed" json:"speed,omitempty"`
	Parse            *int32 `protobuf:"varint,3,opt,name=parse" json:"parse,omitempty"`
	Reason           *int32 `protobuf:"varint,4,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MobileLocationData) Reset()                    { *m = MobileLocationData{} }
func (m *MobileLocationData) String() string            { return proto.CompactTextString(m) }
func (*MobileLocationData) ProtoMessage()               {}
func (*MobileLocationData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MobileLocationData) GetBattery() int32 {
	if m != nil && m.Battery != nil {
		return *m.Battery
	}
	return 0
}

func (m *MobileLocationData) GetSpeed() int32 {
	if m != nil && m.Speed != nil {
		return *m.Speed
	}
	return 0
}

func (m *MobileLocationData) GetParse() int32 {
	if m != nil && m.Parse != nil {
		return *m.Parse
	}
	return 0
}

func (m *MobileLocationData) GetReason() int32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

// 终端位置信息
type LocationReport struct {
	TimeSend         *int64              `protobuf:"varint,1,req,name=time_send" json:"time_send,omitempty"`
	TimeRecv         *int64              `protobuf:"varint,2,req,name=time_recv" json:"time_recv,omitempty"`
	SerialNumber     *int32              `protobuf:"varint,3,opt,name=serial_number" json:"serial_number,omitempty"`
	Tid              *string             `protobuf:"bytes,4,req,name=tid" json:"tid,omitempty"`
	Uuid             *string             `protobuf:"bytes,5,opt,name=uuid" json:"uuid,omitempty"`
	Locations        []*Location         `protobuf:"bytes,6,rep,name=locations" json:"locations,omitempty"`
	Mld              *MobileLocationData `protobuf:"bytes,7,opt,name=mld" json:"mld,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *LocationReport) Reset()                    { *m = LocationReport{} }
func (m *LocationReport) String() string            { return proto.CompactTextString(m) }
func (*LocationReport) ProtoMessage()               {}
func (*LocationReport) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *LocationReport) GetTimeSend() int64 {
	if m != nil && m.TimeSend != nil {
		return *m.TimeSend
	}
	return 0
}

func (m *LocationReport) GetTimeRecv() int64 {
	if m != nil && m.TimeRecv != nil {
		return *m.TimeRecv
	}
	return 0
}

func (m *LocationReport) GetSerialNumber() int32 {
	if m != nil && m.SerialNumber != nil {
		return *m.SerialNumber
	}
	return 0
}

func (m *LocationReport) GetTid() string {
	if m != nil && m.Tid != nil {
		return *m.Tid
	}
	return ""
}

func (m *LocationReport) GetUuid() string {
	if m != nil && m.Uuid != nil {
		return *m.Uuid
	}
	return ""
}

func (m *LocationReport) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *LocationReport) GetMld() *MobileLocationData {
	if m != nil {
		return m.Mld
	}
	return nil
}

func init() {
	proto.RegisterType((*WGS84)(nil), "Report.WGS84")
	proto.RegisterType((*GCJ02)(nil), "Report.GCJ02")
	proto.RegisterType((*MobileCell)(nil), "Report.MobileCell")
	proto.RegisterType((*Wifi)(nil), "Report.Wifi")
	proto.RegisterType((*RFID)(nil), "Report.RFID")
	proto.RegisterType((*TagMacRssi)(nil), "Report.TagMacRssi")
	proto.RegisterType((*Indoor)(nil), "Report.Indoor")
	proto.RegisterType((*IndoorIntensity)(nil), "Report.IndoorIntensity")
	proto.RegisterType((*Location)(nil), "Report.Location")
	proto.RegisterType((*MobileLocationData)(nil), "Report.MobileLocationData")
	proto.RegisterType((*LocationReport)(nil), "Report.LocationReport")
	proto.RegisterEnum("Report.Location_LocationType", Location_LocationType_name, Location_LocationType_value)
	proto.RegisterEnum("Report.Location_FromType", Location_FromType_name, Location_FromType_value)
}

func init() { proto.RegisterFile("Location.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 757 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xdb, 0x8e, 0xdb, 0x36,
	0x10, 0x8d, 0xac, 0x8b, 0xad, 0x91, 0xed, 0x55, 0x98, 0x14, 0x55, 0xdb, 0xb4, 0xd8, 0xa8, 0x40,
	0x63, 0xe4, 0x41, 0x70, 0xd5, 0x45, 0x90, 0xf6, 0x71, 0x13, 0x6f, 0xe0, 0xa2, 0x01, 0x82, 0x8d,
	0x81, 0x6d, 0xfb, 0xb2, 0xa0, 0x25, 0xda, 0x60, 0x41, 0x89, 0x02, 0x49, 0x27, 0xf0, 0x67, 0xf4,
	0x67, 0xfa, 0x13, 0xfd, 0xa9, 0x82, 0x23, 0xc9, 0x97, 0xf4, 0x31, 0x6f, 0x9c, 0xd1, 0xf0, 0xcc,
	0x99, 0x33, 0x87, 0x82, 0xe9, 0x6f, 0xb2, 0xa0, 0x86, 0xcb, 0x3a, 0x6b, 0x94, 0x34, 0x92, 0x04,
	0xb7, 0xac, 0x91, 0xca, 0xa4, 0xd7, 0xe0, 0xdf, 0xbd, 0x79, 0xff, 0xf2, 0x8a, 0x3c, 0x84, 0x40,
	0xd4, 0xdb, 0x7b, 0xf6, 0x22, 0x71, 0x2e, 0x07, 0x33, 0xff, 0x17, 0x67, 0x8e, 0x29, 0x6a, 0x6c,
	0x6a, 0xd0, 0xa7, 0x1e, 0xc1, 0x88, 0x0a, 0xc3, 0xcd, 0xae, 0x64, 0x89, 0x7f, 0xe9, 0x60, 0xd2,
	0x62, 0xbc, 0x79, 0xf5, 0xeb, 0x3c, 0xff, 0x1c, 0x8c, 0x15, 0xc0, 0x5b, 0xb9, 0xe6, 0x82, 0xbd,
	0x62, 0x42, 0x90, 0x18, 0xdc, 0xaa, 0x28, 0x3a, 0x14, 0xf7, 0x6a, 0xfe, 0x82, 0x44, 0xe0, 0x56,
	0x75, 0xd1, 0x82, 0xd8, 0x40, 0xd0, 0x22, 0x71, 0x31, 0x98, 0x42, 0x50, 0x30, 0x21, 0x78, 0x99,
	0x78, 0x18, 0x03, 0x0c, 0xb4, 0x6e, 0x81, 0xd3, 0x1f, 0xc1, 0xbb, 0xe3, 0x1b, 0x8e, 0xb7, 0xa9,
	0xc5, 0x73, 0x66, 0xa1, 0xbd, 0xa0, 0xf9, 0xb6, 0xa6, 0x22, 0x19, 0x60, 0x3c, 0x06, 0x4f, 0x6b,
	0x5e, 0x26, 0xae, 0x8d, 0x52, 0x02, 0xde, 0xed, 0xcd, 0xf2, 0xb5, 0x85, 0xe1, 0x65, 0xcb, 0x20,
	0x7d, 0x0e, 0xb0, 0xa2, 0xdb, 0xb7, 0xb4, 0xb8, 0xd5, 0x9a, 0xdb, 0xfb, 0x06, 0x23, 0xc4, 0x73,
	0xed, 0x7d, 0xa5, 0x35, 0x47, 0x34, 0x27, 0xfd, 0xdb, 0x81, 0x60, 0x59, 0x97, 0x52, 0x2a, 0x72,
	0x01, 0x43, 0xc5, 0xeb, 0x43, 0x25, 0x76, 0x5a, 0x53, 0x63, 0xb0, 0xd2, 0x27, 0x3f, 0x00, 0x98,
	0x03, 0x6a, 0xe2, 0x5e, 0xba, 0xb3, 0x28, 0x27, 0x59, 0xbb, 0x97, 0xec, 0xa4, 0xdf, 0x05, 0x0c,
	0x4b, 0xb6, 0x55, 0x8c, 0xfd, 0x9e, 0x78, 0xb6, 0xc5, 0x31, 0xf1, 0x07, 0x8e, 0x79, 0x92, 0xf8,
	0x33, 0x09, 0x30, 0x31, 0x01, 0x9f, 0x0a, 0xaa, 0xaa, 0x64, 0x88, 0x32, 0x48, 0xb8, 0x68, 0x29,
	0x2d, 0x6b, 0xc3, 0x6a, 0xcd, 0xcd, 0xde, 0x52, 0xe1, 0x15, 0xe3, 0x38, 0x60, 0x4b, 0xcc, 0x2c,
	0x4b, 0x94, 0xf7, 0x38, 0x90, 0xd5, 0xd7, 0x21, 0x31, 0x8c, 0x36, 0xbc, 0xde, 0x32, 0xb5, 0x6c,
	0x15, 0x0e, 0x51, 0x7e, 0x59, 0x24, 0x3e, 0x06, 0x8f, 0x20, 0x92, 0x8a, 0xb3, 0xda, 0xa0, 0xbb,
	0x92, 0xc0, 0x26, 0xd3, 0x7f, 0x5d, 0x18, 0xf5, 0x86, 0x23, 0x3f, 0xc1, 0x58, 0x74, 0x67, 0xb3,
	0x6f, 0x18, 0xb6, 0x9c, 0xe6, 0xdf, 0xf6, 0x93, 0x1e, 0x8c, 0xd9, 0x1f, 0x56, 0xfb, 0x86, 0x91,
	0x67, 0xe0, 0x6d, 0x94, 0xac, 0x90, 0xd1, 0x34, 0xff, 0xea, 0x7f, 0xc5, 0x37, 0x4a, 0x56, 0x58,
	0xf8, 0x04, 0xfc, 0x8f, 0x5b, 0xfd, 0xf2, 0x0a, 0xd7, 0x17, 0xe5, 0x93, 0xbe, 0xb2, 0x75, 0xf5,
	0x13, 0xf0, 0xb7, 0xc5, 0x5f, 0xf3, 0x1c, 0x95, 0x3b, 0xf9, 0xda, 0xfa, 0xf5, 0x29, 0xf8, 0xd6,
	0x3a, 0xd6, 0x2d, 0x67, 0xe2, 0x9f, 0x38, 0xf1, 0x3b, 0x08, 0x38, 0x4a, 0x87, 0xca, 0x46, 0xf9,
	0xb4, 0xaf, 0xe9, 0x76, 0xfc, 0x1c, 0x42, 0xde, 0x8b, 0x8a, 0x6a, 0x47, 0xf9, 0x97, 0xe7, 0x25,
	0x47, 0xcd, 0xbf, 0x01, 0xff, 0x23, 0xdf, 0x70, 0x9d, 0x8c, 0xb0, 0xdd, 0xf8, 0x40, 0x95, 0x6f,
	0x78, 0x2a, 0x61, 0x7c, 0x26, 0x00, 0x40, 0xb0, 0xc0, 0x19, 0xe2, 0x07, 0x78, 0x46, 0xc6, 0xb1,
	0xdd, 0x75, 0xb4, 0x38, 0xf2, 0x8b, 0x07, 0x24, 0x04, 0x7f, 0x61, 0x1d, 0x1b, 0xbb, 0x24, 0x82,
	0xe1, 0xa2, 0x6d, 0x1a, 0x7b, 0xe4, 0x31, 0xc4, 0x8b, 0x4f, 0x18, 0xc4, 0x3e, 0x19, 0x81, 0x77,
	0xb7, 0xbc, 0x59, 0xc6, 0x41, 0x3a, 0x83, 0xd1, 0x41, 0xc4, 0x09, 0x84, 0x8b, 0x15, 0x53, 0x15,
	0xaf, 0xa9, 0x88, 0x1f, 0x60, 0xf8, 0x4e, 0x50, 0xb3, 0x91, 0xaa, 0x8a, 0x9d, 0xf4, 0x3d, 0x90,
	0xb6, 0x63, 0x4f, 0xf0, 0x35, 0x35, 0xd4, 0x9a, 0xce, 0x9a, 0x99, 0xa9, 0x7d, 0xfb, 0x4a, 0xac,
	0xe9, 0x74, 0xc3, 0x58, 0xd9, 0x3d, 0xd2, 0x09, 0xf8, 0x0d, 0x55, 0x9a, 0xe1, 0x62, 0xf0, 0x99,
	0x2a, 0x46, 0xb5, 0xac, 0x71, 0x15, 0x7e, 0xfa, 0x8f, 0x73, 0xfc, 0x27, 0xb5, 0x3a, 0x90, 0x87,
	0x10, 0x1a, 0x5e, 0xb1, 0x7b, 0xcd, 0xea, 0xf6, 0xe5, 0xb9, 0x87, 0x94, 0x62, 0xc5, 0x87, 0xce,
	0x9d, 0x5f, 0xc0, 0x44, 0x33, 0xc5, 0xa9, 0xb8, 0xaf, 0x77, 0xd5, 0x9a, 0xa9, 0x0e, 0x3f, 0x02,
	0xd7, 0xf0, 0xde, 0xa1, 0x63, 0xf0, 0x76, 0x3b, 0x5e, 0xe2, 0xf3, 0x08, 0xc9, 0xf7, 0x10, 0xf6,
	0x06, 0xd4, 0x49, 0x80, 0xda, 0xc7, 0x9f, 0x1a, 0x8a, 0x3c, 0x03, 0xb7, 0x12, 0x65, 0xb7, 0xc2,
	0xaf, 0xcf, 0x9d, 0x70, 0x3a, 0xf7, 0xf5, 0xcf, 0xf0, 0xb4, 0x90, 0x55, 0x56, 0x30, 0x53, 0xd4,
	0xf4, 0x43, 0x26, 0xd6, 0x3a, 0x6b, 0x3a, 0xad, 0xb2, 0x66, 0x9d, 0x55, 0xb2, 0x64, 0xe2, 0xfa,
	0xf1, 0xf9, 0x68, 0xef, 0xec, 0x3f, 0x57, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x99, 0x76,
	0xd1, 0x85, 0x05, 0x00, 0x00,
}
